new packages and upgrade

diff --git a/rdocker/Dockerfile b/rdocker/Dockerfile
--- a/rdocker/Dockerfile
+++ b/rdocker/Dockerfile
@@ -1,102 +1,127 @@
-FROM 42n4/rstudio-dev:latest
-RUN apt-get update && apt-get install -y apt-utils
-RUN apt-get install -y --no-install-recommends libssl-dev libssh2-1-dev zlib1g-dev
-RUN install2.r  \
-    --deps TRUE \
-    devtools    \
-    remotes     \
-    e1071       \
-    rpart       \
-    rpart.plot  \
-    lattice     \
-    ipred       \
-    cluster     \
-    quadprog    \
-    kernlab     \
-    Matrix	\
-    randomForest
-RUN installGithub.r 42n4/dmr.data 42n4/dmr.util 42n4/dmr.claseval 42n4/dmr.stats 42n4/dmr.trans 42n4/dmr.linreg 42n4/dmr.regeval 42n4/dmr.dissim 42n4/dmr.dectree 42n4/dmr.linclas 42n4/dmr.disc 42n4/dmr.kcenters 42n4/dmr.cluseval
-RUN installGithub.r 42n4/dmr.regtree 42n4/dmr.attrsel 42n4/dmr.ensemble 42n4/dmr.kernel 42n4/dmr.bayes 42n4/dmr.hierclus 42n4/dmr.miscost 42n4/dmr.rpartutil
-RUN apt-get install -y --no-install-recommends default-jdk postgresql-9.6 postgresql-client-9.6 libmariadb-client-lgpl-dev postgresql-server-dev-9.6
-RUN apt-get install -y --no-install-recommends libpcre3 libpcre3-dev lzma libbz2-dev liblzma-dev libicu-dev libmagick++-dev libpng-dev
-#apt-get --yes --fix-broken install
-RUN R CMD javareconf
-RUN install2.r  \
-    --deps TRUE \
-    reshape	\
-    sqldf	\
-    dplyr	\
-    party	\
-    rgl	 	\
-    scatterplot3d\
-    fpc		\
-    pvclust	\
-    dendextend	\
-    nFactors	\
-    FactoMineR	\
-    RRF	    	\
-    mclust	\
-    gbm		\
-    mda		\
-    klaR	\
-    caret	\
-    tseries	\
-    forecast	\
-    sets	\
-    TTR
-RUN apt-get install -y tk8.5 libxml2-dev tk-dev
-RUN installGithub.r 42n4/tkrplot
-RUN install2.r  \
-    --deps TRUE \
-    ade4
-RUN install2.r  \
-    --deps TRUE \
-    urca timeSeries fBasics
-RUN installGithub.r 42n4/fUnitRoots
-RUN apt-get install -y --no-install-recommends freeglut3 freeglut3-dev libglew-dev libglu1-mesa libglu1-mesa-dev libgl1-mesa-glx libgl1-mesa-dev
-RUN install2.r  \
-    --deps TRUE \
-    rgl
-RUN apt-get install -y --no-install-recommends texlive-luatex texlive-latex-base
-RUN install2.r  \
-    --deps TRUE \
-    nnet knitr filehash
-RUN installGithub.r yihui/tikzDevice
-RUN install2.r devtools
-RUN rm -rf /tmp/* \
-#&& apt-get remove --purge -y $BUILDDEPS \
-&& apt-get autoremove -y \
-&& apt-get autoclean -y \
-&& rm -rf /var/lib/apt/lists/*
-## Clean up from R source install
-#RUN cd / \
-#  && BUILDDEPS="curl \
-#    default-jdk \
-#    libbz2-dev \
-#    libcairo2-dev \
-#    libcurl4-openssl-dev \
-#    libpango1.0-dev \
-#    libjpeg-dev \
-#    libicu-dev \
-#    libpcre3-dev \
-#    libpng-dev \
-#    libreadline-dev \
-#    libtiff5-dev \
-#    liblzma-dev \
-#    libx11-dev \
-#    libxt-dev \
-#    perl \
-#    subversion \
-#    tcl8.5-dev \
-#    tk8.5-dev \
-#    texinfo \
-#    texlive-fonts-extra \
-#    texlive-extra-utils \
-#    texlive-fonts-recommended \
-#    texlive-latex-recommended \
-#    x11proto-core-dev \
-#    xauth \
-#    xfonts-base \
-#    xvfb \
-#    zlib1g-dev" \
-#latex for tikxdevice
+FROM debian:sid
+
+ARG R_VERSION
+ARG BUILD_DATE
+ENV BUILD_DATE ${BUILD_DATE:-}
+ENV R_VERSION ${R_VERSION:-3.4.0}
+ENV LC_ALL en_US.UTF-8
+ENV LANG en_US.UTF-8
+ENV TERM xterm
+
+## dependencies
+RUN apt-get update \
+  && apt-get install -y --no-install-recommends \
+    bash-completion \
+    ca-certificates \
+    file \
+    fonts-texgyre \
+    g++ \
+    gfortran \
+    gsfonts \
+    libbz2-1.0 \
+    libcurl3 \
+    libicu57 \
+    libjpeg62-turbo \
+    libopenblas-dev \
+    libpangocairo-1.0-0 \
+    libpcre3 \
+    libpng16.16 \
+    libtiff5 \
+    liblzma5 \
+    locales \
+    make \
+    unzip \
+    zip \
+    zlib1g \
+  && echo "en_US.UTF-8 UTF-8" >> /etc/locale.gen \
+  && locale-gen en_US.utf8 \
+  && /usr/sbin/update-locale LANG=en_US.UTF-8 \
+  && BUILDDEPS="curl \
+    default-jdk \
+    libbz2-dev \
+    libcairo2-dev \
+    libcurl4-openssl-dev \
+    libpango1.0-dev \
+    libjpeg-dev \
+    libicu-dev \
+    libpcre3-dev \
+    libpng-dev \
+    libreadline-dev \
+    libtiff5-dev \
+    liblzma-dev \
+    libx11-dev \
+    libxt-dev \
+    perl \
+    tcl8.5-dev \
+    tk8.5-dev \
+    texinfo \
+    texlive-extra-utils \
+    texlive-fonts-recommended \
+    texlive-fonts-extra \
+    texlive-latex-recommended \
+    x11proto-core-dev \
+    xauth \
+    xfonts-base \
+    xvfb \
+    zlib1g-dev" \
+  && apt-get install -y --no-install-recommends $BUILDDEPS \
+  && cd tmp/ \
+  ## Download source code
+  && curl -O https://cran.r-project.org/src/base/R-3/R-${R_VERSION}.tar.gz \
+  ## Extract source code
+  && tar -xf R-${R_VERSION}.tar.gz \
+  && cd R-${R_VERSION} \
+  ## Set compiler flags
+  && R_PAPERSIZE=letter \
+    R_BATCHSAVE="--no-save --no-restore" \
+    R_BROWSER=xdg-open \
+    PAGER=/usr/bin/pager \
+    PERL=/usr/bin/perl \
+    R_UNZIPCMD=/usr/bin/unzip \
+    R_ZIPCMD=/usr/bin/zip \
+    R_PRINTCMD=/usr/bin/lpr \
+    LIBnn=lib \
+    AWK=/usr/bin/awk \
+    CFLAGS="-g -O2 -fstack-protector-strong -Wformat -Werror=format-security -Wdate-time -D_FORTIFY_SOURCE=2 -g" \
+    CXXFLAGS="-g -O2 -fstack-protector-strong -Wformat -Werror=format-security -Wdate-time -D_FORTIFY_SOURCE=2 -g" \
+  ## Configure options
+  ./configure --enable-R-shlib \
+               --enable-memory-profiling \
+               --with-readline \
+               --with-blas="-lopenblas" \
+               --disable-nls \
+               --without-recommended-packages \
+  ## Build and install
+  && make \
+  && make install \
+  ## Add a default CRAN mirror
+  && echo "options(repos = c(CRAN = 'https://cran.rstudio.com/'), download.file.method = 'libcurl')" >> /usr/local/lib/R/etc/Rprofile.site \
+  ## Add a library directory (for user-installed packages)
+  && mkdir -p /usr/local/lib/R/site-library \
+  && chown root:staff /usr/local/lib/R/site-library \
+  && chmod g+wx /usr/local/lib/R/site-library \
+  ## Fix library path
+  && echo "R_LIBS_USER='/usr/local/lib/R/site-library'" >> /usr/local/lib/R/etc/Renviron \
+  && echo "R_LIBS=\${R_LIBS-'/usr/local/lib/R/site-library:/usr/local/lib/R/library:/usr/lib/R/library'}" >> /usr/local/lib/R/etc/Renviron \
+  ## install packages from date-locked MRAN snapshot of CRAN
+  && [ -z "$BUILD_DATE" ] && BUILD_DATE=$(TZ="America/Los_Angeles" date -I) || true \
+  && MRAN=https://mran.microsoft.com/snapshot/${BUILD_DATE} \
+  && echo MRAN=$MRAN >> /etc/environment \
+  && export MRAN=$MRAN \
+  && echo "options(repos = c(CRAN='$MRAN'), download.file.method = 'libcurl')" >> /usr/local/lib/R/etc/Rprofile.site \
+  ## Use littler installation scripts
+  && Rscript -e "install.packages(c('littler', 'docopt'), repo = '$MRAN')" \
+  && ln -s /usr/local/lib/R/site-library/littler/examples/install2.r /usr/local/bin/install2.r \
+  && ln -s /usr/local/lib/R/site-library/littler/examples/installGithub.r /usr/local/bin/installGithub.r \
+  && ln -s /usr/local/lib/R/site-library/littler/bin/r /usr/local/bin/r \
+  ## Clean up from R source install
+  && cd / \
+  && rm -rf /tmp/* \
+  && apt-get remove --purge -y $BUILDDEPS \
+  && apt-get autoremove -y \
+  && apt-get autoclean -y \
+  && rm -rf /var/lib/apt/lists/*
+
+CMD ["R"]
+
+
